namespace Blocto.Sdk.Ethereum.Utility
{
    public enum EthUnitEnum
    {
        Wei,
        Kwei,
        Ada,
        Femtoether,
        Mwei,
        Babbage,
        Picoether,
        Gwei,
        Shannon,
        Nanoether,
        Nano,
        Szabo,
        Microether,
        Micro,
        Finney,
        Milliether,
        Milli,
        Ether,
        Kether,
        Grand,
        Einstein,
        Mether,
        Gether,
        Tether
    }
}