name: Build project

on:
  push:
    branches:
      - "chore/circleci_build"

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS # Build an iOS player.
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug Session
        uses: P3TERX/debugger-action@master

